<?php

namespace ContainerK0qFy8j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GFMZOvGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GFMZOvG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GFMZOvG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'request' => ['privates', '.errored..service_locator.GFMZOvG.Symfony\\Component\\HttpFoundation\\Response', NULL, 'Cannot autowire service ".service_locator.GFMZOvG": it references class "Symfony\\Component\\HttpFoundation\\Response" but no such service exists.'],
        ], [
            'request' => 'Symfony\\Component\\HttpFoundation\\Response',
        ]);
    }
}
